source 'http://rubygems.org'

ruby '2.2.0'

gem 'codeclimate-test-reporter'
gem 'sinatra', git: 'https://github.com/sinatra/sinatra.git'
gem 'json'
gem 'platform-api'
gem 'octokit'
gem 'git'
gem 'pry'
gem 'rspec'
gem 'rack-test'
gem 'vcr'
gem 'webmock'
